/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.FileDialog;
import java.awt.Image;
import static java.awt.image.ImageObserver.HEIGHT;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import objects.User;
import org.Main;
import reading_files.JsonBlock;
import reading_files.JsonReading;

/**
 *
 * @author Francisco Suarez
 */
public class Login extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	public Login() {
		initComponents();
		panel_signup.setVisible(false);
		this.setLocationRelativeTo(null);
		this.setTextFields();
		SetIconsComponents.getInstance().setImages("/img/users.png", lbl_users);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lbl_Logo = new javax.swing.JLabel();
        panel_settings = new javax.swing.JPanel();
        btn_signup = new javax.swing.JLabel();
        btn_signin = new javax.swing.JLabel();
        lbl_sign = new javax.swing.JLabel();
        lbl_users = new javax.swing.JLabel();
        panel_signin = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        txt_passwordLog = new javax.swing.JPasswordField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_carnetLog = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_sign1 = new javax.swing.JLabel();
        panel_signup = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txt_password = new javax.swing.JPasswordField();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_career = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_carnet = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_sign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closingInstance(evt);
            }
        });

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        background.add(lbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, -1));

        panel_settings.setBackground(new java.awt.Color(255, 255, 255));
        panel_settings.setLayout(null);

        btn_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signupMouseClicked(evt);
            }
        });
        panel_settings.add(btn_signup);
        btn_signup.setBounds(410, 30, 100, 50);

        btn_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signinMouseClicked(evt);
            }
        });
        panel_settings.add(btn_signin);
        btn_signin.setBounds(300, 30, 110, 50);

        lbl_sign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sign_up.png"))); // NOI18N
        panel_settings.add(lbl_sign);
        lbl_sign.setBounds(300, 30, 220, 50);

        lbl_users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_usersOpenSettings(evt);
            }
        });
        panel_settings.add(lbl_users);
        lbl_users.setBounds(40, 30, 70, 70);

        background.add(panel_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 540, 120));

        panel_signin.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator11.setBackground(new java.awt.Color(153, 153, 153));

        txt_passwordLog.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        txt_passwordLog.setToolTipText("");
        txt_passwordLog.setBorder(null);
        txt_passwordLog.setOpaque(false);
        txt_passwordLog.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordLogFocusGained(evt);
            }
        });
        txt_passwordLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordLogActionPerformed(evt);
            }
        });

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setText("Ingrese una contraseña");
        jTextField6.setBorder(null);
        jTextField6.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 74, 84));
        jLabel7.setText("Password");

        txt_carnetLog.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        txt_carnetLog.setForeground(new java.awt.Color(153, 153, 153));
        txt_carnetLog.setBorder(null);
        txt_carnetLog.setOpaque(false);

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(64, 74, 84));
        jLabel12.setText("Carnet");

        btn_sign1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_sign1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log_in.png"))); // NOI18N
        btn_sign1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signIn(evt);
            }
        });

        javax.swing.GroupLayout panel_signinLayout = new javax.swing.GroupLayout(panel_signin);
        panel_signin.setLayout(panel_signinLayout);
        panel_signinLayout.setHorizontalGroup(
            panel_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_signinLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panel_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_passwordLog, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_signinLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btn_sign1)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(panel_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_signinLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panel_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(txt_carnetLog, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_signinLayout.setVerticalGroup(
            panel_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_signinLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txt_passwordLog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_sign1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_signinLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(1, 1, 1)
                    .addGroup(panel_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_carnetLog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_signinLayout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 239, Short.MAX_VALUE)))
        );

        background.add(panel_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 530, 340));

        panel_signup.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));

        txt_password.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        txt_password.setToolTipText("");
        txt_password.setBorder(null);
        txt_password.setOpaque(false);
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
        });
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText("Ingrese una contraseña");
        jTextField5.setBorder(null);
        jTextField5.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 74, 84));
        jLabel5.setText("Password");

        txt_career.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        txt_career.setForeground(new java.awt.Color(153, 153, 153));
        txt_career.setBorder(null);
        txt_career.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(64, 74, 84));
        jLabel6.setText("Carrera");

        txt_surname.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        txt_surname.setForeground(new java.awt.Color(153, 153, 153));
        txt_surname.setBorder(null);
        txt_surname.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 74, 84));
        jLabel3.setText("Apellido");

        txt_name.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        txt_name.setForeground(new java.awt.Color(153, 153, 153));
        txt_name.setBorder(null);
        txt_name.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 74, 84));
        jLabel4.setText("Nombre");

        txt_carnet.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        txt_carnet.setForeground(new java.awt.Color(153, 153, 153));
        txt_carnet.setBorder(null);
        txt_carnet.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(64, 74, 84));
        jLabel8.setText("Carnet");

        btn_sign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_sign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log_up.png"))); // NOI18N
        btn_sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUp(evt);
            }
        });

        javax.swing.GroupLayout panel_signupLayout = new javax.swing.GroupLayout(panel_signup);
        panel_signup.setLayout(panel_signupLayout);
        panel_signupLayout.setHorizontalGroup(
            panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_signupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_career, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_signupLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btn_sign)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_signupLayout.setVerticalGroup(
            panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_signupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(1, 1, 1)
                .addGroup(panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_signupLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addGroup(panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_signupLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_signupLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addGroup(panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_career, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_signupLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        background.add(panel_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 530, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
		// TODO add your handling code here:
		txt_password.setText("");
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordLogActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordLogActionPerformed

    private void txt_passwordLogFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordLogFocusGained
		// TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordLogFocusGained

    private void btn_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signinMouseClicked
		// TODO add your handling code here:
		panel_signup.setVisible(false);
		panel_signin.setVisible(true);
		lbl_sign.setIcon(new ImageIcon(getClass().getResource("/img/sign_up.png")));
    }//GEN-LAST:event_btn_signinMouseClicked

    private void btn_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signupMouseClicked
		// TODO add your handling code here:
		panel_signin.setVisible(false);
		panel_signup.setVisible(true);
		lbl_sign.setIcon(new ImageIcon(getClass().getResource("/img/sign_in.png")));
    }//GEN-LAST:event_btn_signupMouseClicked

    private void signUp(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUp
		// TODO add your handling code here:
		Alerts a = new Alerts();
		String carnet = txt_carnet.getText();
		String name = txt_name.getText();
		String surname = txt_surname.getText();
		String career = txt_career.getText();
		String password = txt_password.getText();
		boolean flag = validateTXTs(new String[]{carnet, name, surname, career, password});
		if (flag) {
			User user = new User(Integer.parseInt(carnet), name, surname, career, password);
			if (Main.hashTable.insert(user)) {
				resetFormInsertBook(new javax.swing.JTextField[]{txt_carnet, txt_name, txt_surname, txt_career, txt_password});
				a.define("Usuario registrado correctamente");
			} else {
				a.define("El carnet ya esta registrado en el sistema");
			}
		} else {
			a.define("Existen campos invalidos, por favor inserte los datos necesarios.");
		}
		a.setVisible(true);
    }//GEN-LAST:event_signUp

    private void signIn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signIn
		// TODO add your handling code here:
		Alerts a = new Alerts();
		String carnet = txt_carnetLog.getText();
		String password = new String(txt_passwordLog.getPassword());
		boolean flag = validateTXTs(new String[]{carnet, password});
		if (flag) {
			User user = Main.hashTable.search(Integer.parseInt(carnet));
			if (user != null && user.isPassword(password)) {
				resetFormInsertBook(new javax.swing.JTextField[]{txt_carnetLog, txt_passwordLog});
				a.define("Inicio de sesion correcto");
				Main.user = carnet;
				Home h = new Home();
				h.setVisible(true);
				dispose();
				return;
			} else {
				a.define("El sistema no tiene registros de tu credenciales");
			}
		} else {
			a.define("Existen campos invalidos, por favor inserte los datos necesarios.");
		}
		a.setVisible(true);
    }//GEN-LAST:event_signIn

    private void lbl_usersOpenSettings(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersOpenSettings
		// TODO add your handling code here:
		FileDialog dialog = new FileDialog(this, "Seleccione un archivo", FileDialog.LOAD);
		dialog.setBounds(WIDTH / 2, HEIGHT / 2, 800, 800);
		dialog.setVisible(true);
		dialog.setLocationRelativeTo(null);
		if (dialog.getFile() != null) {
			String directory = dialog.getDirectory();
			String filename = dialog.getFile();
			String route = directory + filename;
			JsonReading.getInstance().jsonUsers(route);
		} else {
			System.out.println("No Seleccionó Archivo");
		}
		JsonBlock.getInstance().createBlock();
    }//GEN-LAST:event_lbl_usersOpenSettings

    private void closingInstance(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closingInstance
		// TODO add your handling code here:
		//Cuando se cierre la instancia procedemos a eliminar de la lista este nodo de la red
		Settings_Form.getInstance().deleteNetwork();
		//Seteamos la lista de nodos en la red
		Settings_Form.getInstance().setNetworks();
    }//GEN-LAST:event_closingInstance

	//Metodo para configurar mis textField
	private ValidateJTextField validate_Txt;

	void setTextFields() {
		validate_Txt = new ValidateJTextField();
		validate_Txt.containsNumbers(txt_carnet);
		validate_Txt.containsNumbers(txt_carnetLog);
	}

	public boolean validateTXTs(String[] txts) {
		//Obtenemos los textos
		for (String txt : txts) {
			String aux = txt.trim();
			if (aux.isEmpty()) {
				return false;
			}
		}
		return true;
	}

	public void resetFormInsertBook(javax.swing.JTextField[] txts) {
		//Obtenemos los textos
		for (JTextField txt : txts) {
			txt.setText("");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	void optionsBG() {
		ImageIcon logo = new ImageIcon(getClass().getResource("/img/logo.png"));
		Icon icon = new ImageIcon(logo.getImage().getScaledInstance(lbl_Logo.getWidth(), lbl_Logo.getHeight(), Image.SCALE_DEFAULT));
		lbl_Logo.setIcon(icon);
		this.repaint();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel btn_sign;
    private javax.swing.JLabel btn_sign1;
    private javax.swing.JLabel btn_signin;
    private javax.swing.JLabel btn_signup;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_sign;
    private javax.swing.JLabel lbl_users;
    private javax.swing.JPanel panel_settings;
    private javax.swing.JPanel panel_signin;
    private javax.swing.JPanel panel_signup;
    private javax.swing.JTextField txt_career;
    private javax.swing.JTextField txt_carnet;
    private javax.swing.JTextField txt_carnetLog;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_passwordLog;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
}
