/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import nodes.Simple_Node;
import objects.Network;
import org.Main;
import reports.Report;

/**
 *
 * @author Francisco Suarez
 */
public class Reports_UI extends javax.swing.JFrame {

	/**
	 * Creates new form Reports_UI
	 */
	private Report rep;

	public Reports_UI() {
		initComponents();
		this.rep = new Report();
		this.setLocationRelativeTo(null);
		this.confNav();
	}

	void confNav() {
		SetIconsComponents.getInstance().setImages("/img/nav.jpg", nav);
		SetIconsComponents.getInstance().setImages("/img/logo_nav.png", nav_logo);
		SetIconsComponents.getInstance().setImages("/img/book.png", lbl_library);
		SetIconsComponents.getInstance().setImages("/img/rep.png", lbl_reports);
		SetIconsComponents.getInstance().setImages("/img/back.png", btn_back);
		SetIconsComponents.getInstance().setImages("/img/log_out.png", btn_logOut);
		this.jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		this.jComboBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		this.jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
		this.jComboBox2.addItem("Ninguna");
		this.jComboBox2.setSelectedIndex(0);
		Simple_Node aux = Main.treeAVL.getCategories().getFirst();
		while (aux != null) {
			this.jComboBox2.addItem(aux.getData());
			aux = aux.getNext();
		}
		this.lbl_category.setVisible(false);
		this.jComboBox2.setVisible(false);
		this.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_add_book1 = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        nav_logo = new javax.swing.JLabel();
        lbl_library = new javax.swing.JLabel();
        lbl_reports = new javax.swing.JLabel();
        btn_logOut = new javax.swing.JButton();
        btn_reports = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_Report = new javax.swing.JLabel();
        nav = new javax.swing.JLabel();
        lbl_category = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closingInstance(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btn_add_book1.setBackground(new java.awt.Color(102, 0, 0));
        btn_add_book1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btn_add_book1.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_book1.setText("Abrir imagen");
        btn_add_book1.setFocusPainted(false);
        btn_add_book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_book1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add_book1);
        btn_add_book1.setBounds(860, 780, 165, 50);

        btn_back.setBackground(new java.awt.Color(51, 51, 51));
        btn_back.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        btn_back.setForeground(new java.awt.Color(219, 170, 50));
        btn_back.setBorderPainted(false);
        btn_back.setContentAreaFilled(false);
        btn_back.setFocusPainted(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(280, 60, 80, 80);
        jPanel1.add(nav_logo);
        nav_logo.setBounds(60, 10, 190, 170);
        jPanel1.add(lbl_library);
        lbl_library.setBounds(370, 60, 80, 80);
        jPanel1.add(lbl_reports);
        lbl_reports.setBounds(510, 60, 80, 80);

        btn_logOut.setBackground(new java.awt.Color(51, 51, 51));
        btn_logOut.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        btn_logOut.setForeground(new java.awt.Color(219, 170, 50));
        btn_logOut.setBorderPainted(false);
        btn_logOut.setContentAreaFilled(false);
        btn_logOut.setFocusPainted(false);
        btn_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logOut);
        btn_logOut.setBounds(1410, 60, 90, 90);

        btn_reports.setBackground(new java.awt.Color(51, 51, 51));
        btn_reports.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        btn_reports.setForeground(new java.awt.Color(219, 170, 50));
        btn_reports.setText("Reportes");
        btn_reports.setBorderPainted(false);
        btn_reports.setContentAreaFilled(false);
        btn_reports.setFocusPainted(false);
        jPanel1.add(btn_reports);
        btn_reports.setBounds(560, 70, 240, 60);

        jLabel33.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(64, 74, 84));
        jLabel33.setText("#SELECCIONA UN REPORTE");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(20, 250, 370, 30);

        jComboBox1.setBackground(new java.awt.Color(18, 30, 49));
        jComboBox1.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Reportes", "Arbol AVL: Categorias", "Arbol B: LIbros en una categoira", "Tabla de Dispersion: Usuarios del sistema", "Recorrido PreOrden del AVL", "Recorrido InOrden del AVL", "Recorrido PostOrden del AVL", "Lista de nodos de la red", "Log de cambios (Blockchain)" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.setFocusable(false);
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(20, 300, 390, 43);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        lbl_Report.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Report.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lbl_Report.setForeground(new java.awt.Color(64, 74, 84));
        jScrollPane1.setViewportView(lbl_Report);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 210, 1080, 560);
        jPanel1.add(nav);
        nav.setBounds(0, 0, 1560, 200);

        lbl_category.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        lbl_category.setForeground(new java.awt.Color(64, 74, 84));
        lbl_category.setText("#SELECCIONA UNA CATEGORIA");
        jPanel1.add(lbl_category);
        lbl_category.setBounds(20, 360, 370, 30);

        jComboBox2.setBackground(new java.awt.Color(18, 30, 49));
        jComboBox2.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguna" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox2.setFocusable(false);
        jComboBox2.setOpaque(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(20, 410, 390, 43);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutActionPerformed
		// TODO add your handling code here:
		Main.user = "";
		dispose();
		Login log = new Login();
		log.setVisible(true);
    }//GEN-LAST:event_btn_logOutActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
		// TODO add your handling code here:
		dispose();
		Home h = new Home();
		h.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
		// TODO add your handling code here:
		this.lbl_Report.setText("");
		this.lbl_Report.setIcon(null);
		this.jComboBox2.setVisible(false);
		this.lbl_category.setVisible(false);
		String graph = "";
		String dot = "";
		openImg = "";
		switch (this.jComboBox1.getSelectedIndex()) {
			case 1:
				graph = Main.treeAVL.getDOT();
				dot = rep.generateTB(graph, "Arbol AVL: Categorias");
				rep.generateImage(dot, "avl");
				setImageViewer("avl");
				break;
			case 2:
				this.jComboBox2.setVisible(true);
				this.lbl_category.setVisible(true);
				break;
			case 3:
				graph = Main.hashTable.getDOT();
				dot = rep.generateTB(graph, "Tabla de dispersion: Usuarios");
				rep.generateImage(dot, "hash");
				setImageViewer("hash");
				break;
			case 4:
				graph = Main.treeAVL.getPreOrder();
				dot = rep.generateLR(graph, "Recorrido PreOrden AVL");
				rep.generateImage(dot, "preOrder");
				setImageViewer("preOrder");
				break;
			case 5:
				graph = Main.treeAVL.getInOrder();
				dot = rep.generateLR(graph, "Recorrido InOrden AVL");
				rep.generateImage(dot, "inOrder");
				setImageViewer("inOrder");
				break;
			case 6:
				graph = Main.treeAVL.getPostOrder();
				dot = rep.generateLR(graph, "Recorrido PostOrden AVL");
				rep.generateImage(dot, "postOrder");
				setImageViewer("postOrder");
				break;
			case 7:
				Simple_Node aux = Main.networkNodes.getFirst();
				while (aux != null) {
					graph += "\"" + ((Network) aux.getData()).getInfo();
					if (aux.getNext() != null) {
						graph += "\"->\"" + ((Network) aux.getNext().getData()).getInfo();
					}
					graph += "\";\n";
					aux = aux.getNext();
				}
				dot = rep.generateLR(graph, "Lista de Nodos en la red.");
				rep.generateImage(dot, "networks");
				setImageViewer("networks");
				break;
			case 8:
				graph = Main.blockchainInstance.getBlocksDOT();
				dot = rep.generateLR(graph, "Bloques generados");
				rep.generateImage(dot, "blocks");
				setImageViewer("blocks");
				break;
		}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
		// TODO add your handling code here:
		if (this.jComboBox2.getSelectedIndex() == 0) {
			this.lbl_Report.setText("");
			this.lbl_Report.setIcon(null);
		} else {
			String category = this.jComboBox2.getSelectedItem().toString();
			String graph = Main.treeAVL.search(Main.treeAVL.getRoot(), category).getReportTreeB();
			String dot = rep.generateTB(graph, "Arbol B: " + category);
			rep.generateImage(dot, "btree");
			setImageViewer("btree");
		}
    }//GEN-LAST:event_jComboBox2ActionPerformed

	void setImageViewer(String img) {
		try {
			Thread.sleep(1000);
			openImg = img + ".png";
			ImageIcon icon = new ImageIcon(img + ".png");
			lbl_Report.setIcon(null);
			lbl_Report.setIcon(icon);
			Thread.sleep(1000);
			icon.getImage().flush();
		} catch (Exception e) {
			System.out.println("Error en el set ImageViewer");
		}
	}

    private void closingInstance(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closingInstance
		// TODO add your handling code here:
		//Cuando se cierre la instancia procedemos a eliminar de la lista este nodo de la red
		Settings_Form.getInstance().deleteNetwork();
		//Seteamos la lista de nodos en la red
		Settings_Form.getInstance().setNetworks();
    }//GEN-LAST:event_closingInstance

	String openImg = "";
    private void btn_add_book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_book1ActionPerformed
		// TODO add your handling code here:
		if (!openImg.equals("")) {
			openImage(openImg);
		}
    }//GEN-LAST:event_btn_add_book1ActionPerformed

	void openImage(String img) {
		try {
			File f = new File(img);
			Desktop dt = Desktop.getDesktop();
			dt.open(f);
		} catch (IOException ex) {
			Logger.getLogger(Reports_UI.class.getName()).log(Level.SEVERE, null, ex);
		}
		System.out.println("Done.");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Reports_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Reports_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Reports_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Reports_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Reports_UI().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_book1;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_logOut;
    private javax.swing.JButton btn_reports;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Report;
    private javax.swing.JLabel lbl_category;
    private javax.swing.JLabel lbl_library;
    private javax.swing.JLabel lbl_reports;
    private javax.swing.JLabel nav;
    private javax.swing.JLabel nav_logo;
    // End of variables declaration//GEN-END:variables
}
